# Generated by Django 3.2.4 on 2021-06-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poi',
            name='poi_info',
            field=models.JSONField(blank=True, default='', null=True, verbose_name='Информация'),
        ),
    ]
